version: "3.8"

services:
  alexmak-pro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alexmak-pro
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
